title: Bita Ashoori | Data Engineer
description: Cloud-Native Pipelines • BI Solutions • AI Enthusiast
theme: jekyll-theme-cayman

# Optional favicon — place favicon.ico in root or assets folder and uncomment below
# favicon: /favicon.ico

# GitHub Pages compatibility
markdown: kramdown
show_downloads: False
